require:
 - rubocop-minitest
 - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Exclude:
  - test/**/*.rb

Metrics/ClassLength:
  Exclude:
  - test/**/*.rb

Metrics/MethodLength:
  Max: 20
  Exclude:
  - test/**/*.rb

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ParallelAssignment:
  Enabled: false

Layout/LineLength:
  Max: 120
